### ISSUE TITLE
MacOS build problems

### ISSUE THREAD

**Issue by materialvision** [Fyfe93/RAVE-audition#4]
Thanks for sharing this great repo. With my limited experience with cmake, I get into some trouble building with cmake and xcode when in the build folder, I first run the two commands mkdir build; cd build
cmake .. -DCMAKE_BUILD_TYPE=Release, and then with the next I get an error :

cmake -G Xcode -B build

CMake Error: The source directory "/Users/espensommereide/Documents/github/RAVE-audition/build" does not appear to contain CMakeLists.txt.

So I have tried to add .. to get the CMakeLists file but still seems to be problems with the folder structure, like a doubling of build folders. 
Any hints as to what is the best way of doing this?

**Comment by ZodiacFRA** [comment]
I think you're not in the build folder, but at the repo's root, try using 
`cd build` before

**Comment by materialvision** [comment]
Thanks, but as you see from the error I am in the build folder when I have this problem.

**Comment by materialvision** [comment]
Ok, I figured out that the cmake -G Xcode -B build should be run from the root without any of the prior commands.
